"""
Script that takes a .pkl test file generated by the mmpose/tools/test.py script
and performs Pose2Sim 3D triangulation using multiple camera views, on pred_instances and gt_instances.

ex: '/mmpose/test_real_trampo/20260202_161130/preds.pkl'
"""

import argparse
import pickle
import os
import numpy as np
from pathlib import Path
import toml

import matplotlib.pyplot as plt
from matplotlib.lines import Line2D
import cv2
import itertools

import itertools as it
import pandas as pd
import logging
from tqdm import tqdm

from Pose2Sim.triangulation import triangulation_from_best_cameras, recap_triangulate, make_trc, indices_of_first_last_non_nan_chunks
from Pose2Sim.common import interpolate_zeros_nans

def computeP(calib_file, undistort=False, cams=None):
    calib = toml.load(calib_file)
    if cams is None:
        cal_keys = [c for c in calib.keys() 
                    if c not in ['metadata', 'capture_volume', 'charuco', 'checkerboard'] 
                    and isinstance(calib[c],dict)]
    else:
        cal_keys = []
        for cam in cams:
            match_key = None
            for k in calib.keys():
                if cam in k or k in cam:
                    match_key = k
                    break
            if match_key:
                cal_keys.append(match_key)
            else:
                cal_keys.append(cam)
                
    P = []
    for cam in cal_keys:
        if cam not in calib:
            for k in calib.keys():
                if cam in k or k in cam:
                    cam = k
                    break
        K = np.array(calib[cam]['matrix'])
        if undistort:
            S = np.array(calib[cam]['size'])
            dist = np.array(calib[cam]['distortions'])
            optim_K = cv2.getOptimalNewCameraMatrix(K, dist, [int(s) for s in S], 1, [int(s) for s in S])[0]
            Kh = np.block([optim_K, np.zeros(3).reshape(3,1)])
        else:
            Kh = np.block([K, np.zeros(3).reshape(3,1)])
        R, _ = cv2.Rodrigues(np.array(calib[cam]['rotation']))
        T = np.array(calib[cam]['translation'])
        H = np.block([[R,T.reshape(3,1)], [np.zeros(3), 1 ]])
        P.append(Kh @ H)
    return P

def retrieve_calib_params(calib_file, cams=None):
    calib = toml.load(calib_file)
    if cams is None:
        cal_keys = [c for c in calib.keys() 
                    if c not in ['metadata', 'capture_volume', 'charuco', 'checkerboard'] 
                    and isinstance(calib[c],dict)]
    else:
        cal_keys = []
        for cam in cams:
            match_key = None
            for k in calib.keys():
                if cam in k or k in cam:
                    match_key = k
                    break
            if match_key:
                cal_keys.append(match_key)
            else:
                cal_keys.append(cam)
                
    S, K, dist, optim_K, inv_K, R, R_mat, T = [], [], [], [], [], [], [], []
    for c, cam in enumerate(cal_keys):
        if cam not in calib:
            for k in calib.keys():
                if cam in k or k in cam:
                    cam = k
                    break
        S.append(np.array(calib[cam]['size']))
        K.append(np.array(calib[cam]['matrix']))
        dist.append(np.array(calib[cam]['distortions']))
        optim_K.append(cv2.getOptimalNewCameraMatrix(K[c], dist[c], [int(s) for s in S[c]], 1, [int(s) for s in S[c]])[0])
        inv_K.append(np.linalg.inv(K[c]))
        R.append(np.array(calib[cam]['rotation']))
        R_mat.append(cv2.Rodrigues(R[c])[0])
        T.append(np.array(calib[cam]['translation']))
    calib_params = {'S': S, 'K': K, 'dist': dist, 'inv_K': inv_K, 'optim_K': optim_K, 'R': R, 'R_mat': R_mat, 'T': T}
    return calib_params

def extract_keypoints_from_preds(preds, cams=[], use_gt=False):
    '''
    Extract pred_instances or gt_instances keypoints from dict output, 
    in the order of the body model hierarchy.

    INPUTS:
    - preds: list of dict. Predictions from the model.
    - n_cams: int
    - use_gt: bool. If True, use gt_instances instead of pred_instances.

    OUTPUTS:
    - x_files, y_files, likelihood_files: [[[[list of coordinates] * n_cams ] * nb_persons_to_detect] * n_frames]
    '''

    # Extract sequence, camera, and frame components from predictions
    data_dict = {}
    for res in preds:
        path = res['img_path']
        dir_name = os.path.basename(os.path.dirname(path))
        filename = os.path.basename(path)
        
        if '-Camera' in dir_name:
            seq = dir_name.split('-Camera')[0]
            cam = dir_name
            frame_part = filename.replace('frame_', '').replace('.png', '').replace('.jpg', '').replace('.jpeg', '')
        else:
            parts = filename.split('-')
            if len(parts) >= 3:
                seq = parts[0]
                cam = parts[1]
                frame_part = parts[2].replace('frame_', '').replace('.png', '').replace('.jpg', '').replace('.jpeg', '')
            else:
                continue
                
        data_dict.setdefault(seq, {}).setdefault(frame_part, {})[cam] = res

    if not preds:
        return []

    # Infer base path from first sample
    first_path = preds[0]['img_path']
    if 'images/' in first_path:
        base_path = first_path.split('images/')[0]
    else:
        base_path = os.path.dirname(os.path.dirname(first_path)) + '/'
    print('base_path:', base_path)

    seqs = sorted(list(data_dict.keys()))
    print('seqs:', seqs)
    print('cams:', cams)

    output = []
    for seq in seqs:
        print('Processing sequence:', seq)
        if len(cams) == 0:
            cameras = sorted(list(set(cam for f in data_dict[seq].values() for cam in f.keys())))
        else:
            cameras = cams

        frames = sorted(list(data_dict[seq].keys()))

        x_files, y_files, likelihood_files = [], [], []
        for f in frames:
            x_cam, y_cam, likelihood_cam = [], [], []
            for c in cameras:
                res = data_dict[seq][f].get(c)
                if res is None:
                    # Handle missing prediction
                    x_cam.append(np.full(17, np.nan))  # Assuming 17 keypoints
                    y_cam.append(np.full(17, np.nan))
                    likelihood_cam.append(np.full(17, 0.0))
                else:
                    if use_gt:
                        keypoints = res['gt_instances']['keypoints'].squeeze()
                        keypoints_visible = res['gt_instances']['keypoints_visible'].squeeze()
                        x_cam.append(keypoints[:, 0])
                        y_cam.append(keypoints[:, 1])
                        likelihood_cam.append(keypoints_visible)
                    else:
                        keypoints = res['pred_instances']['keypoints'].squeeze()
                        keypoint_scores = res['pred_instances']['keypoint_scores'].squeeze()
                        x_cam.append(keypoints[:, 0])
                        y_cam.append(keypoints[:, 1])
                        likelihood_cam.append(keypoint_scores)

            x_files.append([x_cam])
            y_files.append([y_cam])
            likelihood_files.append([likelihood_cam])
        
        print('Frames:', len(x_files), 'Nb persons:', len(x_files[0]), 'Cameras:', len(x_files[0][0]), 'Keypoints:', len(x_files[0][0][0]))

        keypoints = (x_files, y_files, likelihood_files)
        output.append((keypoints, frames, base_path, seq))

    return output

def plot_xy_coordinates(x_files, y_files, likelihood_files, cams, frames, base_path, seq, frame_to_plot=0):
    person_to_plot = 0         # since you currently store 1 person per frame

    n_cams = len(x_files[frame_to_plot][person_to_plot])

    joint_names = [
        "Nose", "L Eye", "R Eye", "L Ear", "R Ear",
        "L Shoulder", "R Shoulder", "L Elbow", "R Elbow",
        "L Wrist", "R Wrist", "L Hip", "R Hip",
        "L Knee", "R Knee", "L Ankle", "R Ankle"
    ]

    n_joints = len(joint_names)
    cmap = plt.get_cmap("tab20")  # good distinct colors
    joint_colors = [cmap(i % 20) for i in range(n_joints)]

    fig, axes = plt.subplots(3, 3, figsize=(16, 8))
    axes = axes.flatten()

    for cam_idx in range(n_cams):
        ax = axes[cam_idx]

        x = x_files[frame_to_plot][person_to_plot][cam_idx]
        y = y_files[frame_to_plot][person_to_plot][cam_idx]
        conf = likelihood_files[frame_to_plot][person_to_plot][cam_idx]

        # Reconstruct image path
        cam_name = cams[cam_idx]
        frame_name = frames[frame_to_plot]
        img_path = os.path.join(base_path, f'{seq}-{cam_name}-{frame_name}.png')

        if os.path.exists(img_path):
            img = cv2.imread(img_path)
            img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
            ax.imshow(img)
        else:
            ax.set_title(f"{cam_name} (missing img)")
            ax.axis("off")
            continue

        # Plot keypoints
        for j in range(len(x)):
            if conf[j] > 0.2:
                ax.scatter(x[j], y[j], color=joint_colors[j], s=15)

        ax.set_title(f"Cam {cam_name}")
        ax.axis("off")

    legend_elements = [
        Line2D([0], [0], marker='o', color='w',
            label=joint_names[i],
            markerfacecolor=joint_colors[i], markersize=8)
        for i in range(n_joints)
    ]

    fig.legend(handles=legend_elements,
            loc='center right',
            title="Joints",
            fontsize=9)

    # Hide unused axes
    for i in range(n_cams, len(axes)):
        axes[i].axis("off")

    plt.tight_layout()
    plt.show()


def triangulate_all(config_dict, calib_file, keypoints, n_cams=8, cams=None, trc_path=None):
    '''
    For each frame
    For each keypoint
    - Triangulate keypoint
    - Reproject it on all cameras
    - Take off cameras until requirements are met
    Interpolate missing values
    Create trc file
    Print recap message
    
     INPUTS: 
    - a calibration file (.toml extension)
    - json files for each camera with indices matching the detected persons
    - a Config.toml file
    - a skeleton model
    
    OUTPUTS: 
    - a .trc file with 3D coordinates
    '''
    likelihood_threshold = config_dict.get('triangulation').get('likelihood_threshold_triangulation')
    interpolation_kind = config_dict.get('triangulation').get('interpolation')
    interp_gap_smaller_than = config_dict.get('triangulation').get('interp_if_gap_smaller_than')
    remove_incomplete_frames = config_dict.get('triangulation').get('remove_incomplete_frames', False)
    sections_to_keep = config_dict.get('triangulation').get('sections_to_keep')
    min_chunk_size = config_dict.get('triangulation').get('min_chunk_size', 5)
    fill_large_gaps_with = config_dict.get('triangulation').get('fill_large_gaps_with')

    P = computeP(calib_file, cams=cams)
    calib_params = retrieve_calib_params(calib_file, cams=cams)
    
    keypoints_names = [
        "Nose", "L Eye", "R Eye", "L Ear", "R Ear",
        "L Shoulder", "R Shoulder", "L Elbow", "R Elbow",
        "L Wrist", "R Wrist", "L Hip", "R Hip",
        "L Knee", "R Knee", "L Ankle", "R Ankle"
    ]
    keypoints_nb = len(keypoints_names)
    keypoints_idx = list(range(keypoints_nb))

    # left/right swapped keypoints
    try:
        keypoints_names_swapped = ['L'+keypoint_name[1:] if keypoint_name.startswith('R') else 'R'+keypoint_name[1:] if keypoint_name.startswith('L') else keypoint_name for keypoint_name in keypoints_names]
        keypoints_names_swapped = [keypoint_name_swapped.replace('right', 'left') if keypoint_name_swapped.startswith('right') else keypoint_name_swapped.replace('left', 'right') if keypoint_name_swapped.startswith('left') else keypoint_name_swapped for keypoint_name_swapped in keypoints_names_swapped]
        keypoints_idx_swapped = [keypoints_names.index(keypoint_name_swapped) for keypoint_name_swapped in keypoints_names_swapped] # find index of new keypoint_name
    except:
        keypoints_names_swapped = keypoints_names
        keypoints_idx_swapped = keypoints_idx
        logging.warning('No left/right swap was performed.')

    f_range = [0, len(keypoints[0])]  # all frames
    nb_persons_to_detect = 1

    Q = [[[np.nan]*3]*keypoints_nb for n in range(nb_persons_to_detect)]
    Q_old = [[[np.nan]*3]*keypoints_nb for n in range(nb_persons_to_detect)]
    error = [[] for n in range(nb_persons_to_detect)]
    nb_cams_excluded = [[] for n in range(nb_persons_to_detect)]
    id_excluded_cams = [[] for n in range(nb_persons_to_detect)]
    Q_tot, error_tot, nb_cams_excluded_tot, cam_excluded_count, id_excluded_cams_tot = [], [], [], [], []
    interp_frames, non_interp_frames, f_range_trimmed = [], [], []
    trc_paths, c3d_paths = [], []

    for f in tqdm(range(*f_range), desc='Triangulating frames'):
        x_files, y_files, likelihood_files = keypoints[0][f], keypoints[1][f], keypoints[2][f]

        x_files = np.array(x_files)  # shape: (nb_persons_to_detect, n_cams, keypoints_nb)
        y_files = np.array(y_files)
        likelihood_files = np.array(likelihood_files)

        #print('likelihood:',likelihood_files)

        # Replace likelihood by 0 if under likelihood_threshold
        with np.errstate(invalid='ignore'):
            for n in range(nb_persons_to_detect):

                x_files[n][likelihood_files[n] < likelihood_threshold] = np.nan
                y_files[n][likelihood_files[n] < likelihood_threshold] = np.nan
                likelihood_files[n][likelihood_files[n] < likelihood_threshold] = np.nan

        # Q_old = Q except when it has nan, otherwise it takes the Q_old value
        nan_mask = np.isnan(Q)
        Q_old = np.where(nan_mask, Q_old, Q)
        Q = [[] for n in range(nb_persons_to_detect)]
        error = [[] for n in range(nb_persons_to_detect)]
        nb_cams_excluded = [[] for n in range(nb_persons_to_detect)]
        id_excluded_cams = [[] for n in range(nb_persons_to_detect)]
        
        for n in range(nb_persons_to_detect):
            for keypoint_idx in keypoints_idx:
            # keypoints_nb = 2
            # for keypoint_idx in range(2):
            # Triangulate cameras with min reprojection error
                coords_2D_kpt = np.array( (x_files[n][:, keypoint_idx], y_files[n][:, keypoint_idx], likelihood_files[n][:, keypoint_idx]) )
                coords_2D_kpt_swapped = np.array(( x_files[n][:, keypoints_idx_swapped[keypoint_idx]], y_files[n][:, keypoints_idx_swapped[keypoint_idx]], likelihood_files[n][:, keypoints_idx_swapped[keypoint_idx]] ))

                Q_kpt, error_kpt, nb_cams_excluded_kpt, id_excluded_cams_kpt = triangulation_from_best_cameras(config_dict, coords_2D_kpt, coords_2D_kpt_swapped, P, calib_params) # P has been modified if undistort_points=True

                #print(f'Frame {f}, Person {n}, Keypoint {keypoints_names[keypoint_idx]}: Reprojection error = {error_kpt:.2f} pixels, Cameras excluded = {id_excluded_cams_kpt}')

                Q[n].append(Q_kpt)
                error[n].append(error_kpt)
                nb_cams_excluded[n].append(nb_cams_excluded_kpt)
                id_excluded_cams[n].append(id_excluded_cams_kpt)

        # Add triangulated points, errors and excluded cameras to pandas dataframes
        Q_tot.append([np.concatenate(Q[n]) for n in range(nb_persons_to_detect)])
        error_tot.append([error[n] for n in range(nb_persons_to_detect)])
        nb_cams_excluded_tot.append([nb_cams_excluded[n] for n in range(nb_persons_to_detect)])
        id_excluded_cams = [[id_excluded_cams[n][k] for k in range(keypoints_nb)] for n in range(nb_persons_to_detect)]
        id_excluded_cams_tot.append(id_excluded_cams)
            
    # fill values for if a person that was not initially detected has entered the frame 
    Q_tot = [list(tpl) for tpl in zip(*it.zip_longest(*Q_tot, fillvalue=[np.nan]*keypoints_nb*3))]
    error_tot = [list(tpl) for tpl in zip(*it.zip_longest(*error_tot, fillvalue=[np.nan]*keypoints_nb*3))]
    nb_cams_excluded_tot = [list(tpl) for tpl in zip(*it.zip_longest(*nb_cams_excluded_tot, fillvalue=[np.nan]*keypoints_nb*3))]
    id_excluded_cams_tot = [list(tpl) for tpl in zip(*it.zip_longest(*id_excluded_cams_tot, fillvalue=[np.nan]*keypoints_nb*3))]

    # dataframes for each person
    Q_tot = [pd.DataFrame([Q_tot_f[n] for Q_tot_f in Q_tot], index=range(*f_range)) for n in range(nb_persons_to_detect)]
    error_tot = [pd.DataFrame([error_tot_f[n] for error_tot_f in error_tot], index=range(*f_range)) for n in range(nb_persons_to_detect)]
    nb_cams_excluded_tot = [pd.DataFrame([nb_cams_excluded_tot_f[n] for nb_cams_excluded_tot_f in nb_cams_excluded_tot], index=range(*f_range)) for n in range(nb_persons_to_detect)]
    id_excluded_cams_tot = [pd.DataFrame([id_excluded_cams_tot_f[n] for id_excluded_cams_tot_f in id_excluded_cams_tot], index=range(*f_range)) for n in range(nb_persons_to_detect)]

    # Interpolate small missing sections
    for n in range(nb_persons_to_detect):
        if interpolation_kind != 'none':
            try:
                Q_tot[n] = Q_tot[n].apply(interpolate_zeros_nans, axis=0, args=[interp_gap_smaller_than, interpolation_kind])
            except:
                logging.warning(f'Interpolation was not possible for person {n}. This means that not enough points are available, which is often due to a bad calibration.')

        # Determine frames where the person is out of the frame
        error_tot[n]['mean'] = error_tot[n].mean(axis = 1, skipna = not remove_incomplete_frames)
        nb_cams_excluded_tot[n]['mean'] = nb_cams_excluded_tot[n].mean(axis=1)
        first_run_start_min, last_run_end_max = indices_of_first_last_non_nan_chunks(error_tot[n]['mean'], min_chunk_size=min_chunk_size, chunk_choice_method=sections_to_keep)
        f_range_trimmed.append([first_run_start_min, last_run_end_max])

        # Skip person if not correctly triangulated
        if last_run_end_max - first_run_start_min <= min_chunk_size:
            nb_cams_excluded_tot[n] = pd.DataFrame(columns=nb_cams_excluded_tot[n].columns)
            cam_excluded_count.append({})
            interp_frames.append([])
            non_interp_frames.append([])
            trc_paths.append ('')
            logging.info(f'\nPerson {n}: Less than {min_chunk_size} valid frames in a row. Deleting person.')
            continue

        # Trim around good frames
        Q_tot[n] = Q_tot[n].iloc[first_run_start_min:last_run_end_max]
        error_tot[n] = error_tot[n].iloc[first_run_start_min:last_run_end_max]
        nb_cams_excluded_tot[n] = nb_cams_excluded_tot[n].iloc[first_run_start_min:last_run_end_max]
        id_excluded_cams_tot[n] = id_excluded_cams_tot[n].iloc[first_run_start_min:last_run_end_max]
        zero_nan_frames = np.where( Q_tot[n].iloc[:,::3].T.eq(0) | ~np.isfinite(Q_tot[n].iloc[:,::3].T) )
        zero_nan_frames_per_kpt = [zero_nan_frames[1][np.where(zero_nan_frames[0]==k)[0]] for k in range(keypoints_nb)]
        zero_nan_frames_per_kpt = [z[(first_run_start_min < z) & (last_run_end_max > z)] for z in zero_nan_frames_per_kpt]

        # Fill non-interpolated values with last valid one
        if fill_large_gaps_with == 'last_value':
            Q_tot[n] = Q_tot[n].ffill(axis=0).bfill(axis=0)
            Q_tot[n].replace([np.nan, np.inf], 0, inplace=True)
        elif fill_large_gaps_with == 'zeros':
            Q_tot[n].replace([np.nan, np.inf], 0, inplace=True)

        # Create TRC file
        if 'project' not in config_dict:
            config_dict['project'] = {}
        if config_dict['project'].get('project_dir') is None:
            if trc_path:
                parent_dir = os.path.dirname(os.path.abspath(trc_path))
                if os.path.basename(parent_dir).lower() == 'pose-3d':
                    config_dict['project']['project_dir'] = os.path.dirname(parent_dir)
                else:
                    config_dict['project']['project_dir'] = parent_dir
            else:
                config_dict['project']['project_dir'] = '.'
                
        default_trc_path = make_trc(config_dict, Q_tot[n], keypoints_names, id_person=n)
        if trc_path is not None:
            import shutil
            os.makedirs(os.path.dirname(os.path.abspath(trc_path)), exist_ok=True)
            abs_default = os.path.abspath(default_trc_path)
            abs_target = os.path.abspath(trc_path)
            if abs_default != abs_target:
                shutil.copy2(default_trc_path, trc_path)
                # Clean up Pose2Sim's intermediate file to avoid duplicates
                try:
                    os.remove(default_trc_path)
                except Exception:
                    pass
            trc_paths.append(trc_path)
        else:
            trc_paths.append(default_trc_path)

        # IDs of excluded cameras
        frame_count = len(Q_tot[n])
        cam_exclusion_counts = {cam_id: 0 for cam_id in range(n_cams)} # initialize at zero
        for excluded_at_frame in id_excluded_cams_tot[n].values:
            for keypoint_cams in excluded_at_frame:
                if isinstance(keypoint_cams, (list, np.ndarray)):
                    for cam_id in keypoint_cams:
                        if isinstance(cam_id, (int, np.integer)):
                            cam_exclusion_counts[cam_id] += 1
        total_opportunities = frame_count * keypoints_nb
        cam_excluded_count.append({k: v/total_opportunities for k, v in cam_exclusion_counts.items()})

        # Optionally, for each person, for each keypoint, show indices of frames that should be interpolated
        gaps = [np.where(np.diff(zero_nan_frames_per_kpt[k]) > 1)[0] + 1 for k in range(keypoints_nb)]
        sequences = [np.split(zero_nan_frames_per_kpt[k], gaps[k]) for k in range(keypoints_nb)]
        interp_frames.append([[f'{seq[0]}:{seq[-1]}' for seq in seq_kpt if len(seq)<=interp_gap_smaller_than and len(seq)>0] for seq_kpt in sequences])
        non_interp_frames.append([[f'{seq[0]}:{seq[-1]}' for seq in seq_kpt if len(seq)>interp_gap_smaller_than] for seq_kpt in sequences])

    if np.all(np.diff(np.array(f_range_trimmed)) <= min_chunk_size):
        print('No persons have been triangulated. Please check your calibration and your synchronization, or the triangulation parameters in Config.toml.')
        return
    
    if len(error_tot) == 0 or all(len(error_tot[n]) == 0 for n in range(nb_persons_to_detect)):
        print('No valid frames after triangulation. Please check your calibration and your synchronization, or the triangulation parameters in Config.toml.')
        return
    
    # Recap message    
    try:
        mean_error_px, mean_error_mm, mean_cam_excluded = recap_triangulate(config_dict, error_tot, nb_cams_excluded_tot, keypoints_names, cam_excluded_count, interp_frames, non_interp_frames, f_range_trimmed, f_range, trc_paths)
        print('\nTriangulation completed, saved to TRC file(s) at:', trc_paths)
        print(f'\nMean reprojection error across all frames and keypoints: {mean_error_px:.2f} pixels, approximately {mean_error_mm:.2f} mm.')
        print(f'Mean cameras excluded across all frames and keypoints: {mean_cam_excluded:.2f}.')
    except Exception as e:
        logging.warning(f'Could not print triangulation recap: {e}')
        print('\nTriangulation completed, saved to TRC file(s) at:', trc_paths)

    return


def parse_args():
    parser = argparse.ArgumentParser(
        description='Triangulate 3D poses from multi-view 2D pose estimations.')
    parser.add_argument('pkl_file', type=str, help='Path to the .pkl file with 2D pose estimations.')
    parser.add_argument('--n-cams', type=int, default=8, help='Number of cameras used for triangulation (>=3).')
    parser.add_argument(
        '--use-gt',
        action='store_true',
        help='Use ground truth 2D keypoints instead of predicted ones.')
    parser.add_argument(
        '--out-file',
        type=str,
        help='Filepath to save the triangulated 3D poses.')
    parser.add_argument(
        '--config-file',
        type=str,
        default='/home/lea/trampo/MODELS_2D3D/Pose2Sim/Config.toml',
        help='Path to the Pose2Sim configuration file.')
    parser.add_argument(
        '--calib-file',
        type=str,
        default='/home/lea/trampo/MODELS_2D3D/Pose2Sim/Calibration/Calib_all.toml',
        help='Path to the camera calibration file.')
    args = parser.parse_args()
    return args

def run_triangulation(pkl_file, config_file, calib_file, out_file, n_cams=8, use_gt=False):
    # Load 2D pose estimation results from the .pkl file
    with open(pkl_file, 'rb') as f:
        pose2d_results = pickle.load(f)

    print('Loaded {} samples from {}'.format(len(pose2d_results), pkl_file))
    config_dict = toml.load(config_file)
    
    # Extract camera names dynamically from prediction image paths
    detected_cams = set()
    for res in pose2d_results:
        path = res.get('img_path', '')
        dir_name = os.path.basename(os.path.dirname(path))
        if '-Camera' in dir_name:
            detected_cams.add(dir_name)
        else:
            filename = os.path.basename(path)
            if '-Camera' in filename:
                parts = filename.split('-frame_')[0]
                detected_cams.add(parts)

    if detected_cams:
        cameras = sorted(list(detected_cams))
    else:
        cameras = ['Camera1_M11139', 'Camera2_M11140', 'Camera3_M11141', 'Camera4_M11458', 'Camera5_M11459', 'Camera6_M11461', 'Camera7_M11462', 'Camera8_M11463']
        
    cams = cameras[:n_cams]
    out = extract_keypoints_from_preds(pose2d_results, cams=cams, use_gt=use_gt)

    for keypoints, frames, base_path, seq in out:
        print('Triangulating sequence:', seq)
        # Create destination directory if not exists
        os.makedirs(os.path.dirname(os.path.abspath(out_file)), exist_ok=True)
        triangulate_all(config_dict, calib_file, keypoints, n_cams=n_cams, cams=cams, trc_path=out_file)
        break


if __name__ == '__main__':
    args = parse_args()
    with open(args.pkl_file, 'rb') as f:
        pose2d_results = pickle.load(f)
    config_dict = toml.load(args.config_file)
    cameras = ['Camera1_M11139', 'Camera2_M11140', 'Camera3_M11141', 'Camera4_M11458', 'Camera5_M11459', 'Camera6_M11461', 'Camera7_M11462', 'Camera8_M11463']
    threshold = config_dict.get('triangulation', {}).get('reproj_error_threshold_triangulation', 15)
    trc_dir = f'output/pose-3d/{threshold}px/{args.n_cams}cams'
    
    for cam_combination in itertools.combinations(cameras, args.n_cams):
        print('Triangulating from cameras:', cam_combination)
        cams = list(cam_combination)
        cam_names = [f'c{c[6]}_' for c in cams]
        cam_names = ''.join(cam_names)
        n_cams = len(cams)
        use_gt = args.use_gt
        out = extract_keypoints_from_preds(pose2d_results, cams=cams, use_gt=use_gt)

        for keypoints, frames, base_path, seq in out:
            print('Triangulating sequence:', seq)
            if args.out_file is not None:
                trc_path = args.out_file
            else:
                os.makedirs(trc_dir, exist_ok=True)
                pkl_name = args.pkl_file.split('/')[-1].replace('.pkl', '')
                trc_path = f'{trc_dir}/triangulated_{cam_names}{seq}_{"gt" if use_gt else pkl_name}.trc'
            triangulate_all(config_dict, args.calib_file, keypoints, n_cams=n_cams, cams=cams, trc_path=trc_path)

